version: '3'
services:
  main:
    build: .
    volumes:
      - ./config:/home/node/supplier/config
      - ./src:/home/node/supplier/src
      - ./wiki:/home/node/supplier/wiki
      - ./www:/home/node/supplier/www
    command: 'npm run local'

  nginx:
    environment:
      USER_IDENTITY: '{\"id\":\"scott.tiger@example.com\",\"roles\":[\"user\", \"supplier-admin\"],\"supplierId\":\"hard001\"}'
