version: '2'
services:
  nginx:
    image: gr4per/nginx-rp:latest
    ports:
     - "8080:8080"
    depends_on:
     - bnp
    labels:
      SERVICE_NAME: 'nginx'
    extra_hosts:
     - 'consul:172.17.0.1'
  bnp:
    build: ./../bnp
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
     - suppliers
    labels:
      SERVICE_NAME: 'bnp'  # Service name used by Registrator for adding to Consul's service discovery registry.
    volumes:
     - ./../bnp:/home/node/bnp
     - /home/node/bnp/node_modules
  suppliers:
    build: .
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
    labels:
      SERVICE_NAME: 'supplier'  # Service name used by Registrator for adding to Consul's service discovery registry.
      SERVICE_TAGS: 'external'
    volumes:
     - ./../supplierDir:/home/node/supplierDir
     #- /home/node/supplierDir/node_modules
  mysql:
    image: gr4per/mysql
    depends_on:
     - registrator
    labels:
      SERVICE_NAME: 'mysql'  # Service name used by Registrator for adding to Consul's service discovery registry.
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
     - consul
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command: ['-internal', 'consul://localhost:8500']
  consul:
    image: consul:latest
    network_mode: host
    #restart: always
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap-expect=1', '-bind=127.0.0.1', '-client=0.0.0.0']

