// this file was auto generated by duriel, don't manually change it!

const de = require('./de.json');
const en = require('./en.json');
const es = require('./es.json');
const fi = require('./fi.json');
const fr = require('./fr.json');
const it = require('./it.json');
const pl = require('./pl.json');
const pt = require('./pt.json');
const sv = require('./sv.json');

module.exports = {de, en, es, fi, fr, it, pl, pt, sv};
