// this file was auto generated by duriel, don't manually change it!

const de = require('./de.json');
const en = require('./en.json');
const pl = require('./pl.json');

module.exports = {de, en, pl};
