type: object
displayName: SupplierContact
description: Object representing all contacts associated with a given supplier.
properties:
    id:
        type: string
    supplierId:
        type: string
    title:
        type: string
    contactType:
        type: string
    firstName:
        type: string
    lastName:
        type: string
    email:
        type: string
        required: false
    phone:
        type: string
        required: false
    mobile:
        type: string
        required: false
    department:
        type: string
        required: false
    fax:
        type: string
        required: false
    changedBy:
        type: string
    createdBy:
        type: string
example: !include ../examples/SupplierContact.json
