type: object
displayName: SupplierBankAccount
description: Object representing all bank accounts assigned to a given supplier.
properties:
    id:
        type: integer
    supplierId:
        type: string
    accountNumber:
        type: string
        description: The International Bank Account Number (IBAN).
    bankIdentificationCode:
        type: string
        description: Bank Identifier Code (BIC).
    bankCountryKey:
        type: string
        description: The bank's country as in ISO 3166-1 alpha2.
    extBankControlKey:
        type: string
    bankCode:
        type: string
        required: false
    bankName:
        type: string
    isrNumber:
        type: string
        required: false
        description: A 9-digit ISR party number under Swiss IBAN.
    plusgiro:
        type: string
        required: false
        description: Number which is part of Swedish bank account details.
    bankgiro:
        type: string
        required: false
        description: Number which is part of Swedish bank account details.
    createdBy:
        type: string
    changedBy:
        type: string
    createdOn:
        type: string
    changedOn:
        type: string
example: !include ../examples/SupplierBankAccount.json
