version: 2
jobs:
  build_test:
    docker:
      # the Docker image with Cypress preinstalled
      - image: cypress/internal:cy-0.19.4
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Running E2E tests
          command: cypress run --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deployment script
          command: |
            export azureswarm_branch=develop
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then export azureswarm_branch=master; fi
            curl https://raw.githubusercontent.com/gr4per/azureswarm/$azureswarm_branch/buildscript.sh > buildscript.sh
            chmod +x buildscript.sh
            ./buildscript.sh opuscapita/$CIRCLE_PROJECT_REPONAME

  build_base:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Build and push Docker base image
          command: |
            docker build -t opuscapita/$CIRCLE_PROJECT_REPONAME:base -f Dockerfile.base .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push opuscapita/$CIRCLE_PROJECT_REPONAME:base

